//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enot.Helpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public int OrderStatus { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string OrderEquipment { get; set; }
        public string OrderTrouble { get; set; }
        public string OrderTroubleDescription { get; set; }
        public int OrderUser { get; set; }
        public Nullable<int> OrderEmployee { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Users Users { get; set; }
    }
}
